import { useEffect, useState } from "react";
import LegacyReview from "./features-review-legacy";
import { platformRequest, platformUpload, type Conversation, type Course, type LLMConfig, type WorkspaceMessage } from "./api/client";

type View = "chat" | "courses" | "review" | "agent" | "memory" | "projects" | "settings";
const nav: Array<[View, string]> = [["chat","AI 对话"],["courses","课程空间"],["review","复习资料"],["agent","Agent 任务"],["memory","记忆中心"],["projects","项目仓库"],["settings","设置"]];

export default function App() {
  const [view, setView] = useState<View>("chat");
  const [welcome, setWelcome] = useState(() => !localStorage.getItem("campus-ai-welcomed"));
  const [courses, setCourses] = useState<Course[]>([]);
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [active, setActive] = useState<string | null>(null);
  const [messages, setMessages] = useState<WorkspaceMessage[]>([]);
  useEffect(() => { Promise.all([platformRequest<Course[]>("/courses"), platformRequest<Conversation[]>("/conversations")]).then(([a,b]) => { setCourses(a); setConversations(b); }); }, []);
  async function newChat() { const item = await platformRequest<Conversation>("/conversations","POST",{title:"新对话",course_id:courses[0]?.id||null}); setConversations(x=>[item,...x]); setActive(item.id); setMessages([]); setView("chat"); }
  async function openChat(id:string){ setActive(id); setMessages(await platformRequest<WorkspaceMessage[]>(`/conversations/${id}/messages`)); setView("chat"); }
  if (view === "review") return <div className="legacy-module"><button className="back-workspace" onClick={()=>setView("chat")}>← 返回工作台</button><LegacyReview /></div>;
  return <div className="campus-shell">
    {welcome && <Welcome onStart={()=>{localStorage.setItem("campus-ai-welcomed","1");setWelcome(false);}} />}
    <aside className="workspace-sidebar"><div className="workspace-brand"><span>CA</span><div><strong>Campus AI</strong><small>Workspace</small></div></div><button className="new-chat" onClick={newChat}>＋ 新建对话</button><nav>{nav.map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}</button>)}</nav><div className="conversation-list"><small>历史对话</small>{conversations.map(x=><button key={x.id} onClick={()=>openChat(x.id)}>{x.title}</button>)}</div><div className="user-chip"><span>本</span><div><strong>本地工作空间</strong><small>数据保存在当前设备</small></div></div></aside>
    <main className="workspace-main"><header className="workspace-topbar"><div><strong>{nav.find(x=>x[0]===view)?.[1]}</strong><span>{courses[0]?.name||"未选择课程"}</span></div><span>v0.5.1 · BYOK</span></header>{view==="chat"&&<Chat active={active} messages={messages} setMessages={setMessages} onCreate={newChat} onSettings={()=>setView("settings")} />}{view==="courses"&&<Courses courses={courses} setCourses={setCourses}/>} {view==="agent"&&<Agent courses={courses}/>} {view==="memory"&&<Memory courses={courses}/>} {view==="settings"&&<Settings/>} {view==="projects"&&<Empty title="项目仓库" text="代码项目管理与 Diff 能力仍在 Beta Roadmap。"/>}</main>
    <aside className="context-panel"><h3>学习上下文</h3><div className="context-block"><small>当前课程</small><strong>{courses[0]?.name||"创建课程后开始"}</strong></div><div className="context-block"><small>隐私模式</small><p>工作空间数据保存在 SQLite；API Key 只保存在当前浏览器。</p></div><div className="context-block"><small>复习引擎</small><p>ExamForge Review Engine 可继续生成模拟卷、Anki 和多格式导出。</p></div></aside>
  </div>;
}

function Welcome({onStart}:{onStart:()=>void}){return <div className="welcome-overlay"><section><div className="logo-mark">CA</div><h1>Campus AI Workspace</h1><p>你的个人 AI 学习与开发工作台</p><ul><li>支持用户自己的 AI API</li><li>数据保存在本地</li><li>支持课程知识库</li><li>支持 AI Agent 学习任务</li><li>支持 ExamForge 复习资料生成</li></ul><button onClick={onStart}>开始使用</button></section></div>}
function Chat({active,messages,setMessages,onCreate,onSettings}:{active:string|null;messages:WorkspaceMessage[];setMessages:React.Dispatch<React.SetStateAction<WorkspaceMessage[]>>;onCreate:()=>void;onSettings:()=>void}){const[text,setText]=useState("");async function send(){if(!active||!text.trim())return;const value=text;setText("");const result=await platformRequest<{message:WorkspaceMessage;reply:WorkspaceMessage}>(`/conversations/${active}/messages`,"POST",{content:value});setMessages(x=>[...x,result.message,result.reply]);}if(!active)return <section className="empty-workspace"><div className="empty-symbol">✦</div><h1>今天想学习什么？</h1><p>无需注册。连接你自己的模型，或先创建课程知识库和本地复习资料。</p><div className="empty-actions"><button onClick={onCreate}>新建对话</button><button className="secondary" onClick={onSettings}>立即配置 AI</button></div></section>;return <section className="chat-workspace"><div className="message-stream">{messages.map(m=><article key={m.id} className={`message ${m.role}`}><span>{m.role==="user"?"你":"AI"}</span><p>{m.content}</p></article>)}</div><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="询问课程内容，或描述你的学习目标…"/><button onClick={send}>↑</button><small>未配置模型时不会报错；本地知识库与复习功能仍可使用。</small></div></section>}
function Courses({courses,setCourses}:{courses:Course[];setCourses:React.Dispatch<React.SetStateAction<Course[]>>}){const[name,setName]=useState("");const[status,setStatus]=useState("");async function create(){if(!name.trim())return;const x=await platformRequest<Course>("/courses","POST",{name,description:"",exam_date:""});setCourses(v=>[x,...v]);setName("")}async function upload(c:Course,file?:File){if(!file)return;setStatus(`正在解析 ${file.name}…`);const x=await platformUpload<{chunks:number}>(`/courses/${c.id}/files`,file);setStatus(`已建立 ${x.chunks} 个可引用知识块`)}return <section className="module-page"><div className="module-heading"><div><small>COURSE SPACES</small><h1>课程空间</h1><p>上传课件、教材、笔记和往年题，建立本地知识库。</p></div><div className="inline-create"><input value={name} onChange={e=>setName(e.target.value)} placeholder="课程名称"/><button onClick={create}>创建课程</button></div></div>{status&&<div className="index-status">{status}</div>}<div className="course-grid">{courses.map(c=><article key={c.id}><div className="course-color"/><small>本地课程</small><h3>{c.name}</h3><p>{c.description||"资料仅保存在当前工作空间"}</p><label className="file-action">上传并建立索引<input type="file" accept=".pdf,.pptx,.docx,.md,.txt,.png,.jpg,.jpeg" onChange={e=>upload(c,e.target.files?.[0])}/></label><footer><span>真实引用</span><span>本地存储</span></footer></article>)}</div></section>}
function Agent({courses}:{courses:Course[]}){const[goal,setGoal]=useState("");const[tasks,setTasks]=useState<Array<{id:string;goal:string;status:string}>>([]);useEffect(()=>{platformRequest<typeof tasks>("/agent/tasks").then(setTasks)},[]);async function add(){if(!goal.trim())return;const x=await platformRequest<(typeof tasks)[number]>("/agent/tasks","POST",{goal,course_id:courses[0]?.id||null});setTasks(v=>[x,...v]);setGoal("")}return <section className="module-page"><div className="module-heading"><div><small>LEARNING AGENT</small><h1>Agent 任务</h1><p>把学习目标拆成可追踪步骤，高风险工具默认关闭。</p></div></div><div className="agent-create"><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="例如：七天内完成概率论冲刺"/><button onClick={add}>制定计划</button></div>{tasks.map(x=><article className="task-row" key={x.id}><span className="status-dot"/><div><strong>{x.goal}</strong><small>{x.status}</small></div></article>)}</section>}
function Memory({courses}:{courses:Course[]}){const[value,setValue]=useState("");const[items,setItems]=useState<Array<{id:string;content:string;kind:string}>>([]);useEffect(()=>{platformRequest<typeof items>("/memory").then(setItems)},[]);async function add(){if(!value.trim())return;const x=await platformRequest<(typeof items)[number]>("/memory","POST",{content:value,kind:"study_preference",course_id:courses[0]?.id||null});setItems(v=>[x,...v]);setValue("")}return <section className="module-page"><div className="module-heading"><div><small>MEMORY CENTER</small><h1>记忆中心</h1><p>显式管理本地学习偏好。</p></div></div><div className="inline-create"><input value={value} onChange={e=>setValue(e.target.value)} placeholder="例如：我适合先看例题"/><button onClick={add}>保存</button></div>{items.map(x=><article className="memory-row" key={x.id}><small>{x.kind}</small><p>{x.content}</p></article>)}</section>}
function Settings(){const saved=JSON.parse(localStorage.getItem("campus-ai-model")||"null") as LLMConfig|null;const[config,setConfig]=useState<LLMConfig>(saved||{enabled:true,provider:"deepseek",api_key:"",base_url:"https://api.deepseek.com",model:"deepseek-chat"});const[result,setResult]=useState("");function update(key:keyof LLMConfig,value:string){setConfig(x=>({...x,[key]:value}))}function save(){localStorage.setItem("campus-ai-model",JSON.stringify(config));setResult("配置仅保存在当前浏览器。")}async function test(){if(!config.api_key){setResult("请先填写 API Key。");return}setResult("正在由浏览器直接测试连接…");const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(`${(config.base_url||"").replace(/\/$/,"")}/models`,{headers:{Authorization:`Bearer ${config.api_key}`},signal:controller.signal});if(response.ok)setResult("连接成功。Key 未经过 Campus AI Workspace 后端。");else if(response.status===401||response.status===403)setResult("Key 错误或无权限。");else if(response.status===404)setResult("接口或模型服务地址不存在。");else setResult(`服务返回错误（${response.status}）。`)}catch(error){setResult(error instanceof DOMException&&error.name==="AbortError"?"连接超时。":"网络错误或供应商不允许浏览器跨域访问；Key 未上传到本项目服务器。") }finally{clearTimeout(timer)}}function clear(){if(confirm("确认清空本地工作空间？此操作不可撤销。"))platformRequest("/workspace","DELETE").then(()=>location.reload())}return <section className="module-page settings-page"><div className="module-heading"><div><small>LOCAL & BYOK</small><h1>设置</h1><p>开发者不提供统一模型额度。API Key 只保存在当前浏览器。</p></div></div><section className="settings-section"><h2>AI 模型配置</h2><label>供应商<select value={config.provider||"deepseek"} onChange={e=>update("provider",e.target.value)}><option value="deepseek">DeepSeek</option><option value="openai_compatible">OpenAI Compatible</option><option value="openai">OpenAI</option><option value="claude_compatible">Claude Compatible</option></select></label><label>API Key<input type="password" value={config.api_key||""} onChange={e=>update("api_key",e.target.value)} autoComplete="off"/></label><label>Base URL<input value={config.base_url||""} onChange={e=>update("base_url",e.target.value)}/></label><label>模型名称<input value={config.model||""} onChange={e=>update("model",e.target.value)}/></label><div className="setting-actions"><button onClick={save}>保存到本地</button><button className="secondary" onClick={test}>测试连接</button></div>{result&&<p className="setting-result">{result}</p>}</section><section className="settings-section"><h2>数据管理</h2><p>导出文件不包含 API Key。导入功能将在校验格式后开放。</p><div className="setting-actions"><a className="button-link" href="/api/v1/workspace/export">导出工作空间</a><button className="danger" onClick={clear}>清空本地数据</button></div></section></section>}
function Empty({title,text}:{title:string;text:string}){return <section className="empty-workspace"><div className="empty-symbol">◇</div><h1>{title}</h1><p>{text}</p></section>}
